# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(0af1ea6c-2772-4cc9-9459-9e19eb540306)'
    appType: 'webApp'
    WebAppName: 'myWebAppabcdefg123456'
    VirtualApplication: 'html-docs-hello-world'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
